name: Deploy Backend to Railway

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        working-directory: ./backend
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Type check with mypy
        working-directory: ./backend
        run: mypy src --ignore-missing-imports

      - name: Test with pytest
        working-directory: ./backend
        run: |
          pytest tests/ --cov=src --cov-report=xml
        env:
          ENVIRONMENT: testing
          JWT_SECRET_KEY: test-secret-key
          LOG_LEVEL: debug

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway (Production)
        if: github.ref == 'refs/heads/main'
        uses: railway-app/railway@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: percepta-pro-backend
          environment: production
        env:
          RAILWAY_ENVIRONMENT: production

      - name: Deploy to Railway (Staging)
        if: github.ref == 'refs/heads/develop'
        uses: railway-app/railway@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: percepta-pro-backend
          environment: staging
        env:
          RAILWAY_ENVIRONMENT: staging 